[GENERAL_OPTIONS]
YEAR = [1981, 1997]
OVERWRITE = true
CSV_EXIST = false
EDIT = ["re", "free_node", "flatten"]

[GLOBAL]
BASE_PATH = "/home/eve/Development/ParlinfoSpeechScraperSenate/Inputs/hansard/"
INPUT_PATH = "/home/eve/Development/ParlinfoSpeechScraperSenate/Inputs/hansard"
LOG_FILE = "/home/eve/Development/ParlinfoSpeechScraperSenate/SenateCSV/hansard/log.txt"
LOGGING = true
OUTPUT_PATH = "/home/eve/Development/ParlinfoSpeechScraperSenate/SenateCSV/hansard"

[METADATA]
TIME = "09:05:36"
ORIGINAL = "/home/eve/Development/ParlinfoSpeechScraperSenate/Inputs/hansard/hansard.toml"
DATE = "2025-06-30"

[[XML_DIR]]
PATH = "xmls"
