[GENERAL_OPTIONS]
YEAR = [1901, 1901]
OVERWRITE = true
CSV_EXIST = false
EDIT = ["re", "free_node", "flatten"]

[GLOBAL]
BASE_PATH = "/home/eve/Development/ParlinfoSpeechScraperSenate/Inputs/hansard/"
INPUT_PATH = "/home/eve/Development/ParlinfoSpeechScraperSenate/Inputs/hansard"
LOG_FILE = "/home/eve/Development/ParlinfoSpeechScraperSenate/Outputs_House/hansard/log.txt"
LOGGING = true
OUTPUT_PATH = "/home/eve/Development/ParlinfoSpeechScraperSenate/Outputs_House/hansard"

[METADATA]
TIME = "16:21:03"
ORIGINAL = "/home/eve/Development/ParlinfoSpeechScraperSenate/Inputs/hansard/hansard.toml"
DATE = "2025-06-29"

[[XML_DIR]]
PATH = "xmls"
